# Generated by Django 4.2.25 on 2025-10-26 14:35

from django.db import migrations


def migrate_data_forward(apps, schema_editor):
    profiles_profile_model = apps.get_model("profiles", "Profile")
    profile_fn_user_model = apps.get_model("fn_profile", "FnUser")

    for profile in profiles_profile_model.objects.all():
        profile_fn_user_model.objects.create(
            phone=profile.phone,
            affiliation=profile.affiliation,
            superior_department=profile.superior_department,
            date_of_birth=profile.date_of_birth,
            gender=profile.gender,
            address=profile.address,
            avatar=profile.avatar,
            bio=profile.bio,
            password=profile.password,
            username=profile.username,
            id=profile.id,
        )


def migrate_data_backward(apps, schema_editor):
    profile_fn_user_model = apps.get_model("fn_profile", "FnUser")
    profile_fn_user_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("fn_profile", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_data_forward,
            reverse_code=migrate_data_backward,
        ),
    ]
