# Generated by Django 4.2.25 on 2025-10-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("profiles", "0007_alter_profile_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to.",
                related_name="profile_groups",
                related_query_name="profile",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="这个用户的特定权限。",
                related_name="profile_permissions",
                related_query_name="profile",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
