
[canteen]
profiles = [
    ['label','name','email','org_name',["supplier0",'supplier1']],
    ['label0','name0','email0','org_name0',["supplier00",'supplier01']],
]
time_nodes = [
    [2024-02-26, 2024-02-29],
    [2024-03-01, 2024-03-01],
    [2024-03-04, 2024-03-08],
    [2024-03-11, 2024-03-15],
    [2024-03-18, 2024-03-22]
]
recounts = [
    ["*小町*","包",50],
    ["*鸡蛋","件",360],
    ["*三全奶香馒头*","件",8],
    ["*滇雪菜家村上等菜籽油*","件",4],
    ["*今麦郎大今野香辣牛肉面*","件",24],
    ["过桥纯味精","件",25],
    ["牛肉丸","件",4]
]
unit_names = [
    ["*酒","瓶"],
    ["*奶","盒"],
    ["*蛋","个"],
    ["*生抽","瓶"],
    ["挂面","把"],
    ["*牛肉面","包"],
    ["*醋","瓶"],
    ["菜籽油","桶"],
    ["*鸡精","包"],
    ["*味精","包"],
    ["*蘸水","包"],
    ["老干妈*","瓶"]
]

# The end.
