
profiles = [
    ['label','name','email','org_name',["supplier0",'supplier1']],
    ['label0','name0','email0','org_name0',["supplier00",'supplier01']],
]
time_nodes = [
    [2024-02-26, 2024-02-29],
    [2024-03-01, 2024-03-01],
    [2024-03-04, 2024-03-08],
    [2024-03-11, 2024-03-15],
    [2024-03-18, 2024-03-22]
]
food_recounts = [
    ["*小町*","包",50],
    ["*鸡蛋","件",360],
    ["*三全奶香馒头*","件",8],
    ["*滇雪菜家村上等菜籽油*","件",4],
    ["*今麦郎大今野香辣牛肉面*","件",24],
    ["过桥纯味精","件",25],
    ["牛肉丸","件",4]
]
food_unit_names = [
    ["*酒","瓶"],
    ["*奶","盒"],
    ["*蛋","个"],
    ["*生抽","瓶"],
    ["*挂面","把"],
    ["*牛肉面","包"],
    ["*醋","瓶"],
    ["*菜籽油","桶"],
    ["*鸡精","包"],
    ["*味精","包"],
    ["*蘸水","包"],
    ["老干妈*","瓶"],
    ["*馒头","包"]
]
[food_classes]
"肉食类"=[
    "*肉*",
    "*鸡*!*蛋*",
    "*鸭*!*蛋*",
    "*牛*",
    "*羊*",
    "*猪*"
]
"粮食类"=[
    "*面包",
    "*蛋黄派",
    "*面条",
    "*米",
    "*町*",
    "*挂面*",
    "*玉米棒*",
    "*馒*",
    "*包"
]
"蛋奶及糕点类"=[
    "*蛋*!*蛋黄派*",
    "*奶*!*奶香*",
]
"油类"=[
    "*油*!*蚝油*!*花椒油*!*酱油*!*油麦菜*",
]
"调味类"=[
    "*葱*",
    "*姜*",
    "*蒜*!*蒜苔*",
    "*辣*",
    "*香菜*",
    "*糖*",
    "*八角*",
    "*草果*",
    "*花椒*",
    "*老干妈*",
    "*醋*",
    "*蘸*",
    "*酒*",
    "*盐*",
    "*折耳根*",
    "*芹*"
]
"水果类"=[
    "*蕉*",
    "*苹果*",
    "*梨*",
]

# The end.
