
[canteen]
profiles = [
    ['label','name','email','org_name',["supplier0",'supplier1']],
    ['label0','name0','email0','org_name0',["supplier00",'supplier01']],
]
time_nodes = [
    [2024-02-26, 2024-02-29],
    [2024-03-01, 2024-03-01],
    [2024-03-04, 2024-03-08],
    [2024-03-11, 2024-03-15]
]
recounts = [
    ["小町","包",50],
    ["大号鸡蛋=","件",360],
    ["三全奶香馒头","件",8],
    ["滇雪菜家村上等菜籽油","件",4]
]

# The end.
