# Generated by Django 6.0.4 on 2026-04-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fnprofile",
            "0007_alter_fnuser_options_alter_fnuser_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fnuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fnuser",
            name="verification_token",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="fnuser",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Email Address",
            ),
        ),
    ]
