# Generated by Django 6.0.4 on 2026-04-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fnprofile",
            "0008_fnuser_email_verified_fnuser_verification_token_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fnuser",
            name="verification_token",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
