# Generated by Django 6.0.4 on 2026-04-28 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fnprofile", "0009_alter_fnuser_verification_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fnuser",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="fnuser",
            name="verification_token",
        ),
        migrations.AlterField(
            model_name="fnuser",
            name="address",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="地址"
            ),
        ),
        migrations.AlterField(
            model_name="fnuser",
            name="affiliation",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="机构"
            ),
        ),
        migrations.AlterField(
            model_name="fnuser",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={"unique": "This email is already registered."},
                help_text="Primary email address.",
                max_length=256,
                null=True,
                unique=True,
                verbose_name="电子邮件地址",
            ),
        ),
        migrations.AlterField(
            model_name="fnuser",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                unique=True,
                verbose_name="电话号码",
            ),
        ),
        migrations.AlterField(
            model_name="fnuser",
            name="superior_department",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="上级机构"
            ),
        ),
        migrations.CreateModel(
            name="Fnemail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Please enter a valid email address",
                        max_length=255,
                        verbose_name="Email 地址",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the email has been verified",
                        verbose_name="Is verified",
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        blank=True,
                        help_text="Token for email verification",
                        max_length=100,
                        null=True,
                        verbose_name="Verification token",
                    ),
                ),
                (
                    "verification_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the verification email was last sent",
                        null=True,
                        verbose_name="Verification email sent at",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the email was verified",
                        null=True,
                        verbose_name="Verified at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this email address is active",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary email address",
                        verbose_name="Is primary",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建于"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Email",
                "verbose_name_plural": "User Emails",
                "ordering": ["-is_primary", "-is_verified", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_primary", "is_active"],
                        name="fnprofile_f_user_id_db6fe2_idx",
                    ),
                    models.Index(
                        fields=["email", "is_verified"],
                        name="fnprofile_f_email_fb6432_idx",
                    ),
                    models.Index(
                        fields=["created_at"],
                        name="fnprofile_f_created_729789_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "email"),
                        name="unique_user_email",
                        violation_error_message="You have already added this email.",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_active", True), ("is_primary", True)
                        ),
                        fields=("user",),
                        name="unique_user_primary_email",
                        violation_error_message="You can only have one primary email.",
                    ),
                ],
            },
        ),
    ]
