# Generated by Django 6.0.4 on 2026-05-04 17:12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fnprofile", "0010_remove_fnuser_email_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fnemail",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="Please enter a valid email address",
                max_length=256,
                verbose_name="Email 地址",
            ),
        ),
        migrations.AlterField(
            model_name="fnemail",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="fnemail",
            name="verification_token",
            field=models.CharField(
                blank=True,
                help_text="Token for email verification",
                max_length=256,
                null=True,
                verbose_name="Verification token",
            ),
        ),
    ]
