# Generated by Django 6.0.4 on 2026-05-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fnprofile", "0011_alter_fnemail_email_alter_fnemail_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fnemail",
            options={
                "ordering": ["-is_primary", "-is_verified", "-created_at"],
                "verbose_name": "用户电子邮件",
                "verbose_name_plural": "用户电子邮件",
            },
        ),
        migrations.RemoveConstraint(
            model_name="fnemail",
            name="unique_user_email",
        ),
        migrations.AlterField(
            model_name="fnemail",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="请输入有效的电子邮箱地址",
                max_length=256,
                verbose_name="电子邮件地址",
            ),
        ),
        migrations.AlterField(
            model_name="fnemail",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="是否电子邮件地址已激活",
                verbose_name="已激活",
            ),
        ),
        migrations.AlterField(
            model_name="fnemail",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="是否该邮件地址是主邮件地址",
                verbose_name="是主邮件地址",
            ),
        ),
        migrations.AlterField(
            model_name="fnemail",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="邮箱地址是否已被验证",
                verbose_name="已被验证",
            ),
        ),
        migrations.AlterField(
            model_name="fnemail",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新于"),
        ),
        migrations.AlterField(
            model_name="fnemail",
            name="verification_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="上次发送验证邮件的时间。",
                null=True,
                verbose_name="验证邮件发送时间",
            ),
        ),
        migrations.AlterField(
            model_name="fnemail",
            name="verification_token",
            field=models.CharField(
                blank=True,
                help_text="电子邮件的验证令牌",
                max_length=256,
                null=True,
                verbose_name="验证令牌",
            ),
        ),
        migrations.AlterField(
            model_name="fnemail",
            name="verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="该电子邮箱被验证的时间",
                null=True,
                verbose_name="验证于",
            ),
        ),
        migrations.AlterField(
            model_name="fnuser",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={
                    "unique": "该电子邮箱地址已用于注册账号（如果是您的邮箱地址没有被验证可在登录页面验证）。"
                },
                help_text="主邮箱地址。",
                max_length=256,
                null=True,
                unique=True,
                verbose_name="电子邮件地址",
            ),
        ),
        migrations.AddConstraint(
            model_name="fnemail",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_verified", True)),
                fields=("email",),
                name="unique_verified_email",
                violation_error_message="This email has been used by other user.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="fnemail",
            name="unique_user_primary_email",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_primary", True)),
                fields=("user",),
                name="unique_user_primary_email",
                violation_error_message="您只能设置一个电子邮件。",
            ),
        ),
    ]
