# Generated by Django 6.0.4 on 2026-05-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fnprofile", "0012_alter_fnemail_options_and_more"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="fnemail",
            name="unique_verified_email",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_verified", True)),
                fields=("email",),
                name="unique_verified_email",
                violation_error_message="该邮箱地址已被其它用户注册。",
            ),
        ),
    ]
