# Generated by Django 6.0.4 on 2026-05-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fnprofile", "0013_alter_fnemail_unique_verified_email"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fnemail",
            name="unique_user_primary_email",
        ),
        migrations.RemoveIndex(
            model_name="fnemail",
            name="fnprofile_f_user_id_db6fe2_idx",
        ),
        migrations.AddField(
            model_name="fnemail",
            name="is_disabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether this email address is disabled",
                verbose_name="is disabled",
            ),
        ),
        migrations.AddIndex(
            model_name="fnemail",
            index=models.Index(
                fields=["user", "is_primary", "is_disabled"],
                name="fnprofile_f_user_id_f476e2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fnemail",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_disabled", False), ("is_primary", True)
                ),
                fields=("user",),
                name="unique_user_primary_email",
                violation_error_message="您只能设置一个电子邮件。",
            ),
        ),
        migrations.RemoveField(
            model_name="fnemail",
            name="is_active",
        ),
    ]
