# Generated by Django 5.2.14 on 2026-05-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fnprofile", "0014_remove_fnemail_unique_user_primary_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fnemail",
            name="is_disabled",
            field=models.BooleanField(
                default=False,
                help_text="是否该电子邮件地址已禁用",
                verbose_name="已禁用",
            ),
        ),
    ]
