# Generated by Django 6.0.4 on 2026-05-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fnprofile", "0015_alter_fnemail_is_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="fnuser",
            name="logout_token",
            field=models.CharField(
                blank=True,
                help_text="Token of logout.",
                max_length=256,
                null=True,
                verbose_name="Logout token",
            ),
        ),
        migrations.AlterField(
            model_name="fnuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Time of creating."
            ),
        ),
        migrations.AlterField(
            model_name="fnuser",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Time of updating."
            ),
        ),
    ]
