# Generated by Django 6.0.4 on 2026-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fnprofile",
            "0016_fnuser_logout_token_alter_fnuser_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fnuser",
            name="reset_password_token",
            field=models.CharField(
                blank=True,
                help_text="Token of resetting password.",
                max_length=256,
                null=True,
                verbose_name="Reset password token",
            ),
        ),
        migrations.AlterField(
            model_name="fnuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间。"
            ),
        ),
        migrations.AlterField(
            model_name="fnuser",
            name="logout_token",
            field=models.CharField(
                blank=True,
                help_text="退出登录的令牌。",
                max_length=256,
                null=True,
                verbose_name="退出登录令牌",
            ),
        ),
        migrations.AlterField(
            model_name="fnuser",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="更新时间。"
            ),
        ),
    ]
