# Generated by Django 5.2.14 on 2026-05-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fnprofile",
            "0017_fnuser_reset_password_token_alter_fnuser_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fnuser",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={
                    "unique": "该电子邮箱地址已用于注册账号（如果是您的邮箱地址没有被验证可在登录页面验证）。"
                },
                help_text="主邮箱地址。",
                max_length=256,
                null=True,
                verbose_name="电子邮件地址",
            ),
        ),
        migrations.AlterField(
            model_name="fnuser",
            name="reset_password_token",
            field=models.CharField(
                blank=True,
                help_text="重置密码的令牌。",
                max_length=256,
                null=True,
                verbose_name="重置密码令牌",
            ),
        ),
    ]
