# Generated by Django 6.0.4 on 2026-05-24 09:32

from django.db import migrations, models


def fix_empty_emails(apps, schema_editor):
    Fnuser = apps.get_model("fnprofile", "Fnuser")
    Fnuser.objects.filter(email="").update(email=None)


def reverse_fix(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        (
            "fnprofile",
            "0018_alter_fnuser_email_alter_fnuser_reset_password_token",
        ),
    ]

    operations = [
        migrations.RunPython(fix_empty_emails, reverse_fix),
        migrations.AlterField(
            model_name="fnuser",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={
                    "unique": "该电子邮箱地址已用于注册账号（如果是您的邮箱地址没有被验证可在登录页面验证）。"
                },
                help_text="主邮箱地址。",
                max_length=256,
                null=True,
                unique=True,
                verbose_name="电子邮件地址",
            ),
        ),
    ]
