# Generated by Django 6.0.4 on 2026-05-31 02:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fnprofile", "0019_alter_fnuser_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fnemail",
            old_name="verification_sent_at",
            new_name="verification_token_updated_at",
        ),
        migrations.AddField(
            model_name="fnuser",
            name="_temp_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="Fake ID"
            ),
        ),
        migrations.AddField(
            model_name="fnuser",
            name="_temp_id_updated_at",
            field=models.DateTimeField(
                auto_now=True,
                null=True,
                verbose_name="Time of updating temporary ID.",
            ),
        ),
    ]
