# Generated by Django 6.0.4 on 2026-05-31 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "fnprofile",
            "0020_rename_verification_sent_at_fnemail_verification_token_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fnuser",
            name="_temp_id",
        ),
        migrations.RemoveField(
            model_name="fnuser",
            name="_temp_id_updated_at",
        ),
    ]
