# Generated by Django 6.0.4 on 2026-06-03 09:04

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fnprofile", "0021_remove_fnuser__temp_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fnuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "该用户名已存在。"},
                help_text="必填，最多 256 个字符，可包含字母、数字、“@”、“.”、“+”、“-”、“_” 。",
                max_length=256,
                unique=True,
                validators=[
                    django.contrib.auth.validators.UnicodeUsernameValidator()
                ],
                verbose_name="用户名",
            ),
        ),
    ]
