# Generated by Django 6.0.4 on 2026-04-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0025_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="食材大类名"
            ),
        ),
        migrations.AlterField(
            model_name="mealtype",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="餐类名称"
            ),
        ),
    ]
