# Generated by Django 5.2.14 on 2026-05-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0026_alter_category_name_alter_mealtype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumption",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="consumption",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="更新时间"
            ),
        ),
    ]
