# Generated by Django 6.0.4 on 2026-05-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0027_consumption_created_at_consumption_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingredients",
                to="canteen.category",
                verbose_name="大类",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="meal_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingredients",
                to="canteen.mealtype",
                verbose_name="餐类",
            ),
        ),
    ]
