# Generated by Django 6.0.4 on 2026-05-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "canteen",
            "0028_alter_ingredient_category_alter_ingredient_meal_type",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumption",
            name="is_disabled",
        ),
    ]
