# Generated by Django 6.0.4 on 2026-06-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("canteen", "0030_alter_ingredient_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="pin_to_consumptions_top",
        ),
    ]
