# Generated by Django 4.2.25 on 2025-10-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_auto_20251026_2235"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fnuser",
            options={
                "verbose_name": "User Information",
                "verbose_name_plural": "User Information",
            },
        ),
    ]
